### ISSUE TITLE
File Format v3

### ISSUE THREAD

**Issue by ax3l** [ax3l/lines-are-beautiful#15]
The file format was updated to v3. Investigate the changes.

**Comment by lobre** [comment]
Hello,

Apparently, there are answers [here](https://github.com/reHackable/maxio/issues/27).

I've just thrown a look quickly but will try to grasp it better by playing with the device.

Loric

**Comment by lobre** [comment]
I little bit more info.

The extension of encoded files is now `.rm` and we have one `.rm` file per page, meaning the top level object in the binary is now the Layer. Here is the `.zip` file structure for a 2 pages note.

 ```
├── 7f33a26e-3fb6-415a-b18f-814716853013
│   ├── 0-metadata.json
│   ├── 0.rm
│   ├── 1-metadata.json
│   └── 1.rm
├── 7f33a26e-3fb6-415a-b18f-814716853013.content
├── 7f33a26e-3fb6-415a-b18f-814716853013.pagedata
└── 7f33a26e-3fb6-415a-b18f-814716853013.thumbnails
    ├── 0.jpg
    └── 1.jpg
```
And taken from the link I attached in my previous comment, here is the binary format.
```
#  header: 'reMarkable .lines file, version=3          '
#  4 bytes integer: number of layers
#  for each layer: 
#      4 bytes integer: number of strokes
#      for each stroke:
#          4 bytes integer: pen
#          4 bytes integer: colour
#          4 bytes: unknown
#          4 bytes floating point: width
#          4 bytes integer: number of segments
#          for each segment:
#              6 floating point numbers: x, y, speed, direction, width, pressure
```
With strokes being what you call lines and segments what you call points.

Loric

**Comment by ax3l** [comment]
Thanks!

I updated the low-level, per-page read and write handling in #16.

**Comment by ax3l** [comment]
Functionality restored as of #18 :)
